# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WorkingWithJSON' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WorkingWithJSON
	 pod 'Alamofire'
  pod 'UIAlertView+Blocks'
  pod 'Crashlytics'
  pod 'ObjectMapper'
  pod 'PKHUD'
  pod 'SwiftyJSON'

  target 'WorkingWithJSONTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WorkingWithJSONUITests' do
    # Pods for testing
  end

end
